// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bljwbhaudmupnfdxulky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsandiaGF1ZG11cG5mZHh1bGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODA0NTIsImV4cCI6MjA3MDM1NjQ1Mn0.KbFRhAfzIDkFF64db3I9Kvg2bC-DWCh-92jwQug2SOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});